myproject/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static 
from django.conf import settings 
from django.views.static import serve

from . import views

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
    path('posts/', include('posts.urls')), 
    path('users/', include('users.urls')), 
]





# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.posts_list, name='list'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.post_page, name='page'),
]

# let slug url stay at the bottom so that i dont catch new-post url

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return self.title
    
# 

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from . import models

class CreateForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug']

myproject/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Post
from . import forms

def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', { 'posts': posts })

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', { 'post': post })

@login_required(login_url="users:login")
def post_new (request):
    if request.method == 'POST':
        form = forms.CreateForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:list')
    else:
        form = forms.CreateForm()
    return render(request, 'posts/post_new.html', { 'form': form })

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            auth_login(request, form.save())
            return redirect('users:login')
    else: 
        form = UserCreationForm()
    return render(request, 'users/register.html', { 'form': form })


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:list')    
    else: 
        form = AuthenticationForm()
    return render(request, 'users/login.html', { 'form': form })        
             
             
def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        return redirect('home')
             
             
# redirect(request.POST.get('next') next is the name of the hidden input field in login.html
# with that, we catch the url name we initially want to go before logged in and
# redirected to that url instead of redirect('posts:list')           

posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
        <form action="{% url 'posts:new-post' %}" method="post" class="form-with-validation" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Add post</button>
        </form>
    </section>
{% endblock %}

posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section>
        <h1>{{ post.title }}</h1>
        <p>Posted on: {{ post.date }}</p>
        <p>{{ post.body }}</p>
    </section>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
        <h1>Posts</h1>
        {% for post in posts %}
            <article>
                <h2>
                    <a href="{% url 'posts:page' slug=post.slug %}">
                        {{ post.title }}
                    </a>
                </h2>
                <p>Posted on: {{ post.date }} by {{ post.author }}</p>
                <p>{{ post.body }}</p>
            </article>
    </section>
    {% endfor %} 
{% endblock %}

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/" title="home">🏠</a> | 
        <a href="/about" title="about">😀</a> | 
        <a href="{% url 'posts:list' %}" title="posts list">📰</a> | 
        <a href="{% url 'posts:new-post' %}" title="new post">🆕</a> | 
        {% if user.is_authenticated %}
        <form class="logout" action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button class="logout-button" title="logout">👋</button>
        </form>
        {% else %}
        <a href="{% url 'users:login' %}" title="login">🔐</a> |
        <a href="{% url 'users:register' %}" title="register">🚀</a> 
        {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <h1>Login</h1>
    <form action="{% url 'users:login' %}" method="post" class="form-with-validation">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <button class="form-button">Submit</button>
    </form>
{% endblock %}

{% comment %} 
add a hidden input, to gather next page value, if it exists in the url 
{% endcomment %}

users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
    <h1>Register a new User</h1>
    <form action="{% url 'users:register' %}" method="post" class="form-with-validation">
        {% csrf_token %}
        {{ form }}
        <button class="form-button">Submit</button>
    </form>
{% endblock %}